### ISSUE TITLE
Мелкие недочеты

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/FSDSlider#11]
Тут вроде от условия ничего не меняется
![image](https://user-images.githubusercontent.com/46089168/97017228-55747b80-1556-11eb-9948-6207a64c15d9.png)

**Comment by Fr0stmourne** [comment]
![image](https://user-images.githubusercontent.com/46089168/97018590-ffa0d300-1557-11eb-9495-d2e73ca9e1cb.png)

Если может прилететь только undefined помимо значения, то можно деструктурировать вместе с указанием дефолтного варианта:
```
const { id = 'value' } = data;
```

**Comment by Fr0stmourne** [comment]
правило `class-methods-use-this` можно не вырубать, как вариант можешь определить эти методы снаружи класса или вообще вынести в отдельные файлы-хелперы

**Comment by Fr0stmourne** [comment]
Странная конструкция, вроде бы можно просто `else { ... }`, там же только 2 значения
![image](https://user-images.githubusercontent.com/46089168/97349327-67308880-18a0-11eb-8daa-964e93af7a3b.png)

**Comment by Fr0stmourne** [comment]
Тут не очень очевидное вычисление с `BUBBLE_OFFSET`, оно вроде сдвигает на половину какого-то элемента, это можно сделать через css, в текущем варианте если потребуется поменять какие-то размеры в слайдере, надо еще эту штуку не забыть обновить
![image](https://user-images.githubusercontent.com/46089168/97349814-fd64ae80-18a0-11eb-8eed-fe214ed1ddaf.png)

**Comment by sodiqit** [comment]
Ну через css я не знаю как сделать потому что может быть 
![image](https://user-images.githubusercontent.com/47000555/97401376-87009480-1912-11eb-8e93-d0a5b112274d.png)
такой элемент, а может быть шире 
![image](https://user-images.githubusercontent.com/47000555/97401460-ad263480-1912-11eb-8c67-a54b35523b5b.png)
но так зато он сдвигается на ширину и отступ ````BUBBLE_OFFSET````. Просто справа у меня шкала, поэтому я двигаю влево bubble. Да и это не половина элемента это отступ в виде 13px получается

**Comment by Fr0stmourne** [comment]
Так это отступ между чем и чем? через css можно так: помещаешь этот блок с цифрой внутрь бегунка и относительно него просто двигаешь на половину ширины с помощью абсолютного позиционирования и трансформа
