### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by Fr0stmourne** [sodiqit/FSDSlider#9]
- Значение меняется если только перетащить за пределы нового значения, лучше начиная с половины интервала уже менять на ближайшее. И еще в конце происходит что-то странное и 87 меняется на 71
![](https://i.imgur.com/0qmxqIz.gif)

- Если задать mulitplier больше, чем длина шкалы, то первое значение пропадает, с шагом (step) такая же история.
![image](https://user-images.githubusercontent.com/46089168/96565602-4202af80-12cd-11eb-944e-9e5b801c760b.png)

- Если честно, мне не совсем понятно, как должны взаимодействовать step и multiplier, если у них не совпадают значения, например вот тут:
![image](https://user-images.githubusercontent.com/46089168/96565965-b3daf900-12cd-11eb-972f-6419ea40b013.png)

Судя по тому, что шкала при таких настройках работает только при значении multiplier === 1, твоему коду тоже не очень понятно :D Сначала я думал, что этот параметр оставляет только кратные мультиплаеру метки, но это не везде работает, так что я не уверен
Надо это пофиксить, можешь параметры как-то синхронизировать и выключать в настройках соответствующие поля, чтобы например кроме 1 ничего нельзя было поставить, или вместо мультиплаера сделать выбор количества меток на шкале и рассчитывать их по шагу, ну или еще как-то сделать, подумай над этим

- Если задать шаг больше, чем длина шкалы, то ползунок уже не передвинуть

**Comment by Fr0stmourne** [comment]
Если включить второй бегунок, то остается активным поле value, которое вроде бы ничего не делает, но его можно менять, лучше его задизейблить

**Comment by sodiqit** [comment]
Ну multiplier имеет немного другую логику, давай объясню, допустим у нас 
```javascript
const slider = $('.selector').slider({
   min: 0,
   max: 100,
   step: 1,
   showScale: true,
})
```
В итоге получится каша потому что шкала у меня генерируется в зависимости от step, а если увеличить размер шага для шкалы то и используется мультиплаер, т.е если я создам по другому слайдер
```javascript
const slider = $('.selector').slider({
   min: 0,
   max: 100,
   step: 1,
   multiplier: 10,
   showScale: true,
})
```
то получу 
![image](https://user-images.githubusercontent.com/47000555/96991475-ebea7200-1541-11eb-8545-a63582814f31.png)
Я это впринципе в доке показал, так что не считаю это багом, все вроде как логично

**Comment by Fr0stmourne** [comment]
> Ну multiplier имеет немного другую логику, давай объясню, допустим у нас
> 
> ```js
> const slider = $('.selector').slider({
>    min: 0,
>    max: 100,
>    step: 1,
>    showScale: true,
> })
> ```
> 
> В итоге получится каша потому что шкала у меня генерируется в зависимости от step, а если нужно увеличить размер шага для шкалы то и используется мультиплаер, т.е если я создам по другому слайдер
> 
> ```js
> const slider = $('.selector').slider({
>    min: 0,
>    max: 100,
>    step: 1,
>    multiplier: 10,
>    showScale: true,
> })
> ```
> 
> то получу
> ![image](https://user-images.githubusercontent.com/47000555/96991475-ebea7200-1541-11eb-8545-a63582814f31.png)
> Я это впринципе в доке показал, так что не считаю это багом, все вроде как логично. То есть мультиплаер просто инкрементирует шаг в указанное количество раз и рисует шкалу, не мутируя или как то изменяя основный step, то есть он так и будет 1.

Можно было в принципе ограничить количество отрисовываемых шагов, но ладно, пусть будет)

**Comment by Fr0stmourne** [comment]
- Если резко дергать за бегунок, то до предела не доезжает
![](https://i.imgur.com/u4Ws09b.gif)

**Comment by Fr0stmourne** [comment]
Если сначала включить range-режим в первом слайдере, а потом поставить макс. значение -100 например, то бегунки будут с одинаковыми значениями, можно будет передвинуть только по клику по шкале
